import { createFakeApi } from '../ui-harness/fake-api.mjs';
import { startApp, openApp } from '../ui-harness/app.mjs';
import { corpus, opfsRoot, writeFolder } from '../ui-harness/opfs.mjs';
import { runScript, screenshot } from '../ui-harness/evidence.mjs';
await runScript('19-trial','Small trial, human verdicts, explicit full-run preparation, stale categories and provenance',async({checks,evidence,defer})=>{
 const {check}=checks,fake=createFakeApi();fake.categories(['procedures','explainers']);fake.state.seed.settings.pilotSize=2;fake.state.vendors='fake';
 const app=await startApp({fake});defer(()=>app.close());const session=await openApp(app,{hash:'#/'});defer(()=>session.close());
 const {page,picker,watch}=session;
 const capture=async name=>{const path='.local/qa/ui-rebuild/'+name+'.png';await page.locator('[data-testid="stage"]').screenshot({path});return path;};const files=corpus(4),root=opfsRoot('trial');
 await writeFolder(page,root,files);await page.goto(app.url('#/new'));
 await page.waitForSelector('[data-testid="files"]');
 const localId=await page.evaluate(()=>location.hash.split('/')[2]);
 picker.queue(root);await page.locator('button[data-op="files:choose-folder:'+localId+'"]').click();
 await page.locator('[data-testid="files-primary"] [data-feedback][data-state="done"]').waitFor({timeout:30000});await page.locator('[data-testid="files-primary"] button').click();
 await page.waitForSelector('[data-testid="confirm"]');
 await page.getByText('2 of 4 documents selected for this run.',{exact:true}).waitFor();
 check('a collection above the configured size starts with a bounded trial',await page.locator('[data-testid="trial-selection-count"]').textContent()==='2 of 4 documents selected for this run.');
 check('preparation sends no quote or run request',fake.requests.every(r=>r.method==='GET'));
 const selectedOrder=await page.evaluate(async localId=>{
  const {journeyDb}=await import('/persist/journey-db.ts');
  const value=await journeyDb.get('trials',localId),order=[...value.order].reverse(),selected=order.slice(0,2);
  await journeyDb.put('trials',localId,{...value,order,selected});return selected;
 },localId);
 await page.reload();await page.getByText('2 of 4 documents selected for this run.',{exact:true}).waitFor();
 await page.locator('#confirm-limit-blended').fill('5');
 const start=page.locator('button[data-op="confirm:start:'+localId+'"]');await start.click();await start.click({timeout:1000}).catch(()=>{});
 await page.waitForURL(url=>url.hash.endsWith('/progress'));
 const runId=await page.evaluate(()=>location.hash.split('/')[2]);
 await page.waitForFunction(()=>document.querySelector('[data-testid="progress-count"]')===null||document.querySelector('[data-testid="shell-narration-now"]')?.textContent.includes('Sort'),null,{timeout:20000}).catch(()=>{});
 const until=async(fn,label)=>{const end=Date.now()+25000;while(!fn()){if(Date.now()>end)throw new Error('Timed out: '+label);await new Promise(r=>setTimeout(r,50));}};
 await until(()=>fake.getRun(runId)?.status==='running','trial uploads');fake.finish(runId);
 await page.goto(app.url('#/run/'+runId+'/results'));
 await page.waitForSelector('[data-testid="trial-review"] [data-testid="trial-file"]');
 const run=fake.state.runs.get(runId),quote=fake.state.quotes.get(run.quoteId);
 check('one start creates a pilot campaign and uploads only selected documents',run.campaign.role==='pilot'&&run.docs.size===2&&quote.documents.length===2&&fake.requests.filter(r=>r.method==='POST'&&r.path==='/api/runs').length===1);
 check('reloaded selected subset keeps its recorded order through quote, upload and results',
   JSON.stringify(quote.documents.map(d=>d.fingerprint))===JSON.stringify(selectedOrder)&&
   JSON.stringify([...run.docs.values()].sort((a,b)=>a.tag.localeCompare(b.tag)).map(d=>d.fingerprint))===JSON.stringify(selectedOrder));
 check('pretend-vendor provenance is visible on the run',await page.locator('[data-testid="shell-chips"]').textContent().then(t=>t.includes('Pretend models')));
 const confirm=page.locator('button[data-op="trial:confirm:'+runId+'"]');
 check('the completed trial NEXT hint points to trial review',await page.locator('[data-testid="shell-narration-next"]').textContent()==='Review the small trial');
 check('confirmation waits for every automatically filed placement',await confirm.isDisabled());
 const firstFiled=[...run.docs.values()].find(d=>d.decision.ruleId==='R1');
 await page.locator('button[data-op="trial:verdict:'+runId+':'+firstFiled.fingerprint+':wrong"]').click();
 await page.getByRole('button',{name:"Open the editor with this document's evidence",exact:true}).waitFor();
 check('a wrong placement prevents trial confirmation',await page.locator('button[data-op="trial:confirm:'+runId+'"]').count()===0);
 await page.getByRole('button',{name:"Open the editor with this document's evidence",exact:true}).click();
 await page.locator('[data-testid="trial-editor-evidence"]').waitFor();
 check('wrong opens the editor with recorded evidence and no automatic wording change',await page.locator('[data-testid="trial-editor-evidence"]').textContent().then(t=>t.includes('No wording or example is added automatically'))&&fake.requests.every(r=>r.path!=='/api/definitions/drafts'));
 await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(600);
 evidence.wrong=await capture('19-trial-editor-evidence');
 await page.goto(app.url('#/run/'+runId+'/results'));await page.locator('[data-testid="trial-review"]').waitFor();
 const beforeReview=fake.requests.length;
 const entries=[...run.docs.values()].filter(d=>d.decision.ruleId==='R1');
 for(const doc of entries){const right=page.locator('button[data-op="trial:verdict:'+runId+':'+doc.fingerprint+':right"]');await right.click();await page.locator('[data-feedback="trial:verdict:'+runId+':'+doc.fingerprint+':right"][data-state="done"]').waitFor();}
 check('every right verdict is a separate explicit request',fake.requests.slice(beforeReview).filter(r=>r.path.endsWith('/pilot-review')).length===entries.length);
 check('right counts alone never confirm the trial',run.pilotConfirmation===null);
 await confirm.evaluate(button=>{button.click();button.click();});await page.getByRole('button',{name:'Prepare the full run',exact:true}).waitFor();
 check('confirmation records a human decision without another run',run.pilotConfirmation!==null&&fake.state.runs.size===1&&fake.requests.filter(r=>r.path.endsWith('/pilot-confirmation')).length===1);
 await page.waitForFunction(()=>![...document.querySelectorAll('[data-testid="stage"] [data-testid="results-table"] tbody')].some(row=>/Waiting its turn|Not sent yet/.test(row.textContent)));
 check('decided Results rows show outcomes rather than pending stages',!await page.locator('[data-testid="stage"] [data-testid="results-table"]').textContent().then(t=>/Waiting its turn|Not sent yet/.test(t)));
 await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(600);
 evidence.confirmed=await capture('19-trial-confirmed-dark');
 const beforeReload=fake.requests.length;await page.reload();await page.getByRole('button',{name:'Prepare the full run',exact:true}).waitFor();
 check('reload keeps the confirmation and sends no POST',fake.requests.slice(beforeReload).every(r=>r.method==='GET'));
 await page.getByRole('button',{name:'Prepare the full run',exact:true}).click();
 await page.waitForSelector('[data-testid="confirm"]');await page.getByText('4 of 4 documents selected for this run.',{exact:true}).waitFor();
 let fullId=await page.evaluate(()=>location.hash.split('/')[2]);
 check('full preparation visibly includes all originals and trial documents',await page.locator('[data-testid="trial-selection"]').textContent().then(t=>t.includes('including the trial documents')&&t.includes('classified and charged again')));
 check('the full draft needs a fresh spending decision',await page.locator('#confirm-limit-blended').inputValue()===''&&fake.state.runs.size===1);
 const prepared=await page.evaluate(async localId=>{const db=await import('/persist/journey-db.ts');const records=await import('/persist/local-records.ts');return{selection:await db.journeyDb.get('trials',localId),records:(await records.listLocalRecords(localId)).map(r=>({state:r.state,fingerprint:r.fingerprint}))};},fullId);
 check('campaign and full selection persist; prior paid outcomes are not copied',prepared.selection.campaignId===run.campaign.id&&prepared.selection.selected.length===4&&prepared.records.every(r=>r.state!=='uploaded'));
 await page.reload();await page.getByText('4 of 4 documents selected for this run.',{exact:true}).waitFor();
 check('full selection survives reload without starting',fake.state.runs.size===1);
 await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(600);
 evidence.full=await capture('19-trial-full-selection');
 // The full selection can be edited before any spending confirmation.
 await page.locator('[data-testid="trial-selection"] details summary').click();
 await page.locator('[data-trial-document]:checked').last().uncheck();
 await page.getByRole('button',{name:'Use this selection',exact:true}).click();
 await page.getByText('3 of 4 documents selected for this run.',{exact:true}).waitFor();
 check('full selection changes are explicit before spending',await page.locator('[data-testid="trial-selection-count"]').textContent()==='3 of 4 documents selected for this run.');
 await page.getByRole('button',{name:'Select all originals',exact:true}).click();
 await page.getByRole('button',{name:'Use this selection',exact:true}).click();
 await page.locator('#confirm-limit-blended').fill('5');
 await page.locator('button[data-op="confirm:start:'+fullId+'"]').click();await page.waitForURL(url=>url.hash.endsWith('/progress'));
 const fullRunId=await page.evaluate(()=>location.hash.split('/')[2]);
 await until(()=>fake.getRun(fullRunId)?.status==='running','full uploads');
 const fullRun=fake.state.runs.get(fullRunId);
 check('full Start sends every selected original again under the confirmed campaign',
   fullRun.campaign.role==='full'&&fullRun.campaign.id===run.campaign.id&&fullRun.docs.size===4&&selectedOrder.every(fp=>fullRun.docs.has(fp))&&run.docs.size===2);
 fullRun.status='halted';fullRun.halt={code:'E_RUN_HALTED',message:'Stopped for this local test.'};
 await page.reload();await page.locator('button[data-op="progress:retry-unfinished:'+fullRunId+'"]').waitFor();
 await page.locator('button[data-op="progress:retry-unfinished:'+fullRunId+'"]').click();await page.waitForSelector('[data-testid="files"]');
 const retryCampaign=await page.evaluate(async()=>{const keys=await import('/persist/local-keys.ts');return keys.readRetryCampaign(location.hash.split('/')[2]);});
 check('an unfinished full-run retry keeps its campaign without starting',retryCampaign.id===run.campaign.id&&retryCampaign.role==='full'&&fake.state.runs.size===2);
 // Prepare a separate full draft, then change categories before spending.
 await page.goto(app.url('#/run/'+runId+'/results'));await page.getByRole('button',{name:'Prepare the full run',exact:true}).click();
 await page.waitForSelector('[data-testid="confirm"]');await page.getByText('4 of 4 documents selected for this run.',{exact:true}).waitFor();
 fullId=await page.evaluate(()=>location.hash.split('/')[2]);
 // A version changes before a new full quote: the server must refuse, with a plain slot message.
 const active=fake.state.revisions.get(fake.state.active.revisionId);
 const next={...structuredClone(active),id:crypto.randomUUID(),baseRevisionId:active.id};fake.state.revisions.set(next.id,next);fake.state.active.revisionId=next.id;
 await page.locator('#confirm-limit-blended').fill('5');await page.locator('button[data-op="confirm:start:'+fullId+'"]').click();
 await page.locator('[data-feedback="confirm:start:'+fullId+'"][data-state="problem"]').waitFor();
 // If the current preparation noticed category changes first, an additional explicit click reaches the stale-campaign refusal.
 await page.locator('button[data-op="confirm:start:'+fullId+'"]').click();
 await page.waitForTimeout(200);
 check('changed categories cannot use the old trial to start a full run',fake.state.runs.size===2&&await page.locator('[data-feedback="confirm:start:'+fullId+'"]').textContent().then(t=>t.includes('categories changed after this trial')));
 await page.goto(app.url('#/run/'+runId+'/results'));await page.getByRole('button',{name:'Prepare a new trial',exact:true}).waitFor();
 check('stale trial offers a new trial instead of full preparation',await page.getByRole('button',{name:'Prepare the full run',exact:true}).count()===0);
 await page.evaluate(()=>{document.documentElement.dataset.theme='dark';window.scrollTo(0,0);});await page.waitForTimeout(600);evidence.stale=await capture('19-trial-stale-dark');
 await page.getByRole('button',{name:'Prepare a new trial',exact:true}).click();await page.waitForSelector('[data-testid="confirm"]');
 const canaryLocal=await page.evaluate(()=>location.hash.split('/')[2]);
 await page.getByText('2 of 4 documents selected for this run.',{exact:true}).waitFor();
 await page.locator('[data-testid="trial-selection"] details summary').click();
 await page.locator('[data-trial-document]:checked').last().uncheck();
 await page.getByRole('button',{name:'Use this selection',exact:true}).click();
 await page.getByText('1 of 4 documents selected for this run.',{exact:true}).waitFor();
 await page.locator('#confirm-limit-blended').fill('5');await page.locator('button[data-op="confirm:start:'+canaryLocal+'"]').click();
 await page.waitForURL(url=>url.hash.endsWith('/progress'));const canaryRun=await page.evaluate(()=>location.hash.split('/')[2]);
 await until(()=>fake.getRun(canaryRun)?.status==='running','one document canary');
 check('an explicit one-document trial starts a fresh campaign',fake.state.runs.get(canaryRun).docs.size===1&&fake.state.runs.get(canaryRun).campaign.role==='pilot'&&fake.state.runs.get(canaryRun).campaign.id!==run.campaign.id);
 // A separate completed fixture proves zero R1 still requires a click.
 const zero=fake.completed({total:1,outcomes:['R4'],pilot:true});await page.goto(app.url('#/run/'+zero.runId+'/results'));
 await page.getByRole('button',{name:'Confirm the trial',exact:true}).waitFor();
 check('zero R1 never auto-confirms',fake.state.runs.get(zero.runId).pilotConfirmation===null);
 await page.getByRole('button',{name:'Confirm the trial',exact:true}).click();await page.getByRole('button',{name:'Prepare the full run',exact:true}).waitFor();
 check('zero R1 records the explicit confirmation',fake.state.runs.get(zero.runId).pilotConfirmation?.filedCount===0);
 await page.goto(app.url('#/system'));await page.locator('[data-testid="system-vendors"]').waitFor();
 check('Health clearly labels simulated calls and costs',await page.locator('[data-testid="system-vendors"]').textContent().then(t=>t.includes('Pretend models')&&t.includes('simulated costs')));
 check('no uncaught browser errors',watch.record.pageErrors.length===0,watch.record.pageErrors);
 check('no external requests',watch.record.external.length===0,watch.record.external);
 check('fake contracts stay valid',fake.problems.length===0,fake.problems);
 evidence.requests=fake.requests.map(r=>({method:r.method,path:r.path,status:r.status,body:r.path==='/api/quote'?{count:r.body.documents.length,campaign:r.body.campaign}:undefined}));
});
