import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve,relative,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {validateReader,validateConfidence} from '../../core/vendors/validate.ts';
import {verifyModelPolicy} from '../../core/vendors/requests.ts';
import {verifyRecoveredHeadings} from '../../core/digest/recovery.ts';
import * as reader from './contract.mjs';
import {replayReader} from './replay.mjs';
import {normalizeRecoveryManifest,recoveryAdapter} from '../recovery-bakeoff/runtime-contract.mjs';
import {compareReference} from '../recovery-bakeoff/contract.mjs';
const hash=value=>createHash('sha256').update(value).digest('hex');
const parse=bytes=>JSON.parse(bytes.toString().replace(/^\uFEFF/,''));
const requireThat=(condition,message)=>{if(!condition)throw new Error(message);};
export const median=values=>{if(!values.length)return null;const s=[...values].sort((a,b)=>a-b),n=s.length;return n%2?s[(n-1)/2]:(s[n/2-1]+s[n/2])/2;};
const sumKnown=(items,key)=>items.every(v=>Number.isSafeInteger(v[key])&&v[key]>=0)?items.reduce((s,v)=>s+v[key],0):null;
export function assertPrivateOutput(path){const absolute=resolve(path);requireThat(['.local'].some(root=>{const r=relative(resolve(root),absolute);return r!==''&&!r.startsWith('..'+sep)&&r!=='..'&&!r.startsWith(sep)&&!r.includes(':');}),'Output must be under .local.');return absolute;}
export function summarizeRows(rows){return [...new Set(rows.map(r=>r.model))].map(model=>{
 const cells=rows.filter(r=>r.model===model),attempts=cells.flatMap(r=>r.attempts),unknown=attempts.filter(a=>a.costNano===null).length,known=attempts.reduce((v,a)=>v+BigInt(a.costNano??'0'),0n),valid=cells.filter(c=>c.state==='valid').length,agreements=cells.filter(c=>c.provisionalAgreement===true).length;
 const measured=attempts.map(a=>a.latencyMs).filter(v=>Number.isFinite(v)&&v>=0),active=cells.filter(c=>c.attempts.length>0).map(c=>sumKnown(c.attempts,'latencyMs')).filter(v=>v!==null);
 return{model,plannedCells:cells.length,validCells:valid,failedCells:cells.filter(c=>c.state==='failed').length,missingCells:cells.filter(c=>c.state==='missing'||c.state==='pending'||c.state==='running').length,attempts:attempts.length,firstAttemptValidCells:cells.filter(c=>c.state==='valid'&&c.attempts.length===1).length,firstAttemptValidityUnknownCells:cells.filter(c=>c.attempts.length>1).length,provisionalAgreements:agreements,provisionalAgreementDenominator:cells.length,knownCostNano:known.toString(),totalCostNano:unknown?null:known.toString(),unknownCostAttempts:unknown,inputTokens:sumKnown(attempts,'inputTokens'),outputTokens:sumKnown(attempts,'outputTokens'),cachedTokens:sumKnown(attempts,'cachedTokens'),cacheWriteTokens:sumKnown(attempts,'cacheWriteTokens'),reasoningTokens:sumKnown(attempts,'reasoningTokens'),costPerValidCellUsd:!unknown&&valid?Number(known)/1e9/valid:null,costPerProvisionalAgreementUsd:!unknown&&agreements?Number(known)/1e9/agreements:null,attemptLatencyMedianMs:median(measured),attemptLatencyMeasuredCount:measured.length,cellActiveLatencyMedianMs:median(active),cellActiveLatencyMeasuredCount:active.length,latencyBasis:'Attempt latency from runtime; cell active latency is sum of attempt latencies, excluding waits/client/network overhead. Not wall-clock completion latency.'};
});}
async function loadSources(m,kind,referencePath){
 const bytes=await readFile(referencePath),expected=kind==='reader'?m.referenceSha256:m.referenceSha256;requireThat(hash(bytes)===expected,'Frozen reference hash mismatch');const refs=parse(bytes),contexts=new Map();
 for(const source of m.sources){const bytes=await readFile(source.input.file);requireThat(hash(bytes)===source.input.artifactSha256,'Frozen input artifact hash mismatch');const input=parse(bytes);requireThat(hash(input.fullText)===source.textSha256&&input.fingerprint===source.fingerprint,'Frozen text/source identity mismatch');const reference=(kind==='reader'?refs.documents:refs.entries).find(r=>r.id===source.id);requireThat(reference,'Missing frozen source reference');
  let confidence=null;if(kind==='reader'){requireThat(reference.sourceHash===source.fingerprint,'Reference source hash mismatch');const cb=await readFile(source.confidence.file);requireThat(hash(cb)===source.confidence.artifactSha256,'Frozen confidence artifact hash mismatch');confidence=parse(cb).value;validateConfidence(confidence,{pin:confidence.model,typeIds:m.typeFile.types.map(t=>t.id)});}
  contexts.set(source.id,{source,input,reference,confidence});
 }return{contexts,referenceSha256:hash(bytes)};
}
export function pairwiseRows(rows,kind){const pairwise=[];for(const caseId of new Set(rows.map(r=>r.caseId))){const pair=rows.filter(r=>r.caseId===caseId);pairwise.push({caseId,cells:pair.map(r=>r.id),bothValid:pair.length===2&&pair.every(r=>r.state==='valid'),readerYesAgreement:kind==='reader'&&pair.length===2&&pair.every(r=>r.state==='valid')?JSON.stringify([...pair[0].readerYes].sort())===JSON.stringify([...pair[1].readerYes].sort()):null,knownCostDeltaNano:pair.length===2&&pair.every(r=>['valid','failed'].includes(r.state)&&r.attempts.length>0&&r.attempts.every(a=>a.costNano!==null))?(pair[1].attempts.reduce((n,a)=>n+BigInt(a.costNano),0n)-pair[0].attempts.reduce((n,a)=>n+BigInt(a.costNano),0n)).toString():null,deltaOrder:'second listed cell minus first listed cell; frozen order may alternate models'});}return pairwise;}
export function validateReportManifest(frozen,original=null){
 if(frozen.role==='recovery')return normalizeRecoveryManifest(frozen);
 if(!['owner_authorized_access_resume','owner_authorized_access_retry'].includes(frozen.kind))return reader.validateManifest(frozen);
 const base=reader.validateManifest(original??frozen.originalManifest);requireThat(base.id!==frozen.id,'Continuation must have its own campaign identity');
 for(const field of ['actor','baselineVerifiedAt','baselineOpenaiNano','baselineTypesafeNano','limitNano','typeFile','typeHash','sourceManifestSha256','referenceSha256'])requireThat(JSON.stringify(base[field])===JSON.stringify(frozen[field]),'Continuation changed frozen '+field);
 if(frozen.kind==='owner_authorized_access_resume'){requireThat(JSON.stringify(frozen.sources)===JSON.stringify(base.sources),'Continuation changed frozen sources');requireThat(JSON.stringify(frozen.cells)===JSON.stringify(base.cells.slice(1)),'Continuation must contain only the exact nine remaining requests');}
 else{requireThat(frozen.cells?.length===1,'One-shot retry must contain one request');const c=frozen.cells[0],expected=base.cells[1];requireThat(frozen.sources?.length===1&&JSON.stringify(frozen.sources[0])===JSON.stringify(base.sources.find(s=>s.id===expected.caseId)),'Retry source differs from frozen original');requireThat(c.model==='gpt-6-sol'&&JSON.stringify({...c,id:expected.id})===JSON.stringify(expected),'Retry differs from the original frozen Sol request');}
 return frozen;
}
export function composeReaderReports(originalManifest,original,continuation,retry){
 const selected=[original.rows.find(r=>r.id===originalManifest.cells[0].id),...continuation.rows];requireThat(selected.length===10&&selected[0]?.state==='valid','Composite requires original valid Terra plus nine continuation cells');
 for(const [i,c]of originalManifest.cells.entries()){const row=selected[i];requireThat(row?.id===c.id&&row.model===c.model&&row.caseId===c.caseId&&row.bodyHash===c.requestSha256&&(!row.textSha256||row.textSha256===c.textSha256),'Composite changed frozen cell identity/request');}
 const history=[...original.rows.filter(r=>r.id!==selected[0].id&&r.attempts.length>0),...retry.rows.filter(r=>r.attempts.length>0)];requireThat(history.length===2&&history.every(r=>r.model==='gpt-6-sol'&&r.state==='failed'),'Expected both historical failed Sol cells');
 const all=[...selected,...history].flatMap(r=>r.attempts);requireThat(new Set(all.map(a=>a.id)).size===all.length,'Attempt duplicated across composite evidence');const known=all.reduce((v,a)=>v+BigInt(a.costNano??'0'),0n),unknown=all.filter(a=>a.costNano===null).length;
 const perModel=summarizeRows([...selected,...history]).map(v=>({model:v.model,attempts:v.attempts,knownCostNano:v.knownCostNano,totalCostNano:v.totalCostNano,unknownCostAttempts:v.unknownCostAttempts,inputTokens:v.inputTokens,outputTokens:v.outputTokens,reasoningTokens:v.reasoningTokens,cachedTokens:v.cachedTokens,cacheWriteTokens:v.cacheWriteTokens}));return {schemaVersion:1,kind:'reader-composite',generatedAt:new Date().toISOString(),rows:selected,summaries:summarizeRows(selected),historicalRejectedRows:history,allAttemptAccounting:{attempts:all.length,knownCostNano:known.toString(),unknownCostAttempts:unknown,totalCostNano:unknown?null:known.toString(),perModel,denominatorNote:'Accounting includes two historical denied Sol cells; these are not additional unique benchmark documents.'},matrixTerminal:selected.every(r=>['valid','failed'].includes(r.state)),accountingComplete:unknown===0,complete:selected.every(r=>['valid','failed'].includes(r.state))&&unknown===0,reusedFirstCell:{id:selected[0].id,attemptIds:selected[0].attempts.map(a=>a.id)},limitations:['Ten semantic comparison cells: original first Terra reused once plus nine newly authorized continuation cells.','Original denied Sol attempt and denied one-shot retry remain separately visible; their null usage/cost is not zero and is not removed by an admission exception.','Selected-comparison cost excludes those historical attempts; all-attempt total remains unknown while either denied attempt is unaccounted.','Access-denial latency is not model inference latency and is reported only in historical attempt details.','Provisional agent references and this small convenience set do not establish accuracy, calibration or a model winner.','Both note-policy results are retained-Jev counterfactuals; historical source decisions remain unchanged.']};
}
export async function buildReport(manifestPath,statusPath,referencePath,options={}){
 const manifestBytes=await readFile(manifestPath),frozen=parse(manifestBytes),kind=frozen.role==='recovery'?'recovery':'reader',m=validateReportManifest(frozen,options.originalManifest),contract=kind==='recovery'?recoveryAdapter:{...reader,role:'reader'},snapshotBytes=await readFile(statusPath),snapshot=parse(snapshotBytes),s=snapshot.body?.campaign!==undefined?snapshot.body:snapshot;
 requireThat(s&&Array.isArray(s.cells)&&Array.isArray(s.attempts),'Expected immutable GET/status snapshot');const manifestHash=hash(JSON.stringify(m));
 if(s.campaign)requireThat(s.campaign.id===m.id&&s.campaign.actor===m.actor&&s.campaign.manifest_hash===manifestHash,'Snapshot campaign identity/hash mismatch');else requireThat(s.cells.length===0&&s.attempts.length===0,'Missing campaign with existing records');
 const {contexts}=await loadSources(m,kind,referencePath);const expected=new Map(m.cells.map(c=>[c.id,c]));requireThat(new Set(s.cells.map(c=>c.id)).size===s.cells.length&&new Set(s.attempts.map(a=>a.id)).size===s.attempts.length,'Duplicate runtime identity');
 for(const row of s.cells)requireThat(expected.has(row.id)&&row.campaign_id===m.id,'Unrecognized runtime cell');for(const a of s.attempts)requireThat(expected.has(a.cell_id)&&a.campaign_id===m.id,'Unrecognized runtime attempt');
 const rows=[];
 for(const c of m.cells){const context=contexts.get(c.caseId);requireThat(context,'Source context missing');await contract.verifyCellText(m,c,context.input.fullText);const request=contract.requestForCell(m,c,context.input.fullText),bodyHash=hash(request.body);requireThat(bodyHash===c.requestSha256,'Frozen request hash mismatch');const runtime=s.cells.find(r=>r.id===c.id);
  if(runtime){requireThat(runtime.model===c.model&&runtime.text_sha256===c.textSha256,'Runtime source/model mismatch');if(runtime.body_sha256!==null)requireThat(runtime.body_sha256===bodyHash,'Runtime body hash mismatch');requireThat(['pending','running','valid','failed'].includes(runtime.state),'Unknown cell state');}
  const attempts=s.attempts.filter(a=>a.cell_id===c.id).map(a=>{
   requireThat(a.body_sha256===bodyHash&&a.model_requested===c.model,'Attempt body/model mismatch');const usage=a.usage_json===null?null:JSON.parse(a.usage_json);let identityValid=null;if(a.model_returned!==null){try{verifyModelPolicy({id:c.model,policy:'owner_approved_alias',date:'2026-09-23',reason:m.authorization},a.model_returned,kind==='reader'?'reader':'recovery',contract.policy);identityValid=true;}catch{identityValid=false;}}
   const cost=a.cost_nano===null?null:String(a.cost_nano);let inputCostNano=null,outputCostNano=null;if(cost!==null){requireThat(a.raw_key&&a.metadata_key&&identityValid===true,'Accounted attempt lacks raw/model evidence');requireThat(contract.accountAttempt(c.model,{model:a.model_returned,usage},true)===cost,'Recorded usage cost mismatch');inputCostNano=contract.accountAttempt(c.model,{model:a.model_returned,usage:{...usage,output_tokens:0}},true);outputCostNano=(BigInt(cost)-BigInt(inputCostNano)).toString();}
   const token=k=>Number.isSafeInteger(usage?.[k])&&usage[k]>=0?usage[k]:null;const detail=(parent,k)=>Number.isSafeInteger(usage?.[parent]?.[k])&&usage[parent][k]>=0?usage[parent][k]:null;
   return{id:a.id,status:a.status,state:a.state,modelRequested:a.model_requested,modelReturned:a.model_returned,modelIdentityValid:identityValid,bodyHash,rawKey:a.raw_key,metadataKey:a.metadata_key,usage,costNano:cost,inputCostNano,outputCostNano,inputTokens:token('input_tokens'),outputTokens:token('output_tokens'),reasoningTokens:detail('output_tokens_details','reasoning_tokens'),cachedTokens:detail('input_tokens_details','cached_tokens'),cacheWriteTokens:detail('input_tokens_details','cache_write_tokens'),latencyMs:Number.isFinite(a.latency_ms)&&a.latency_ms>=0?a.latency_ms:null,createdAt:a.created_at};
  });
  const row={id:c.id,caseId:c.caseId,model:c.model,state:runtime?.state??'missing',sourceFingerprint:context.source.fingerprint,textSha256:c.textSha256,bodyHash,attempts,provisionalAgreement:null,originalNotes:context.source.notes,originalDecision:context.source.originalDecision};
  const result=runtime?.result_json?JSON.parse(runtime.result_json):null;if(result){requireThat(result.cellId===c.id&&result.status===runtime.state,'Result identity/state mismatch');if(result.status==='failed')row.failureCode=result.code;}
  if(runtime?.state==='valid'){
   requireThat(result?.bodyHash===bodyHash&&Array.isArray(result.attemptIds)&&result.attemptIds.length===attempts.length&&result.attemptIds.every(id=>attempts.some(a=>a.id===id))&&new Set(result.attemptIds).size===attempts.length,'Validated result attempt/hash mismatch');verifyModelPolicy({id:c.model,policy:'owner_approved_alias',date:'2026-09-23',reason:m.authorization},result.value.model,kind==='reader'?'reader':'recovery',contract.policy);requireThat(attempts.find(a=>a.id===result.attemptIds.at(-1))?.modelReturned===result.value.model,'Final returned identity differs from final attempt');row.value=result.value;
   if(kind==='reader'){const typeIds=m.typeFile.types.map(t=>t.id);validateReader(result.value,{pin:result.value.model,typeIds,text:context.input.fullText});const yes=result.value.verdicts.filter(v=>v.is_type).map(v=>v.type_id);row.readerYes=yes;row.reference={bucket:context.reference.provisionalBucket,confidence:context.reference.qualitativeConfidence,ambiguity:context.reference.alternativesAndAmbiguity};row.provisionalAgreement=context.reference.provisionalBucket==='none_of_these'?yes.length===0:yes.length===1&&yes[0]===context.reference.provisionalBucket;row.replay=replayReader({notes:context.source.notes,confidence:{choice:context.confidence.choice,certainty:context.confidence.confidence,noul:context.confidence.nouls}},result.value,typeIds);}
   else{const verification=verifyRecoveredHeadings(context.input.fullText,result.value.headings);requireThat(JSON.stringify(verification)===JSON.stringify(result.value.verification),'Recorded recovery verification mismatch');row.headingQuality=compareReference(context.input.fullText,result.value.headings,context.reference);}
  }rows.push(row);
 }
 const summaries=summarizeRows(rows),pairwise=[];for(const summary of summaries){const cells=rows.filter(r=>r.model===summary.model),attempts=cells.flatMap(c=>c.attempts);for(const field of ['inputCostNano','outputCostNano'])summary[field]=attempts.every(a=>a[field]!==null)?attempts.reduce((n,a)=>n+BigInt(a[field]),0n).toString():null;if(kind==='reader'){summary.historicalRuleCounts={};summary.approvedRuleCounts={};for(const c of cells.filter(c=>c.replay)){for(const [field,policy]of [['historicalRuleCounts','historicalNotePolicy'],['approvedRuleCounts','approvedNotePolicy']]){const id=c.replay[policy].ruleId;summary[field][id]=(summary[field][id]??0)+1;}}}else{for(const field of ['provisionalAgreements','provisionalAgreementDenominator','costPerProvisionalAgreementUsd'])delete summary[field];summary.referenceMetric='heading categories, not document classification agreement';summary.headingCounts={definiteMatched:0,definiteMissing:0,optionalMatched:0,otherExactLines:0,rejected:0,duplicateCandidates:0};for(const c of cells.filter(c=>c.headingQuality)){for(const field of ['definiteMatched','definiteMissing','optionalMatched','otherExactLines','rejected'])summary.headingCounts[field]+=c.headingQuality[field].length;summary.headingCounts.duplicateCandidates+=c.headingQuality.duplicateCandidateCount;}}}pairwise.push(...pairwiseRows(rows,kind));
 return{schemaVersion:1,kind,generatedAt:new Date().toISOString(),manifestSha256:manifestHash,manifestFileSha256:hash(manifestBytes),statusFileSha256:hash(snapshotBytes),statusPath,referenceFileSha256:hash(await readFile(referencePath)),campaign:s.campaign,matrixTerminal:rows.every(r=>['valid','failed'].includes(r.state)),accountingComplete:rows.every(r=>r.attempts.every(a=>a.costNano!==null)),complete:rows.every(r=>['valid','failed'].includes(r.state)&&r.attempts.every(a=>a.costNano!==null)),rows,summaries,pairwise,limitations:['Agent provisional references, not human-corrected ground truth; no accuracy/calibration or winner claim.','Convenience cases are small, selected, not population-representative; failed/missing cells remain in planned denominators.','Final structured outputs and accounting are revalidated from status; raw response bytes are referenced by immutable keys, not present in this snapshot.','Multi-attempt first-attempt schema validity is unknown from status alone.','Cell active latency sums measured attempt latency and excludes waits; it is not wall-clock completion time.','Jev and prior recovery are retained replay inputs and sunk costs, not new inference; historical and approved policy outcomes are counterfactuals.']};
}
export function markdown(r){const money=v=>v===null?'unknown':(Number(v)/1e9).toFixed(9);const lines=[`# ${r.kind.startsWith('reader')?'Reader':'Recovery'} paired comparison`,``,r.complete?'All planned cells have terminal records and recorded usage is accounted.':r.matrixTerminal?'All planned comparison cells are terminal; accounting remains incomplete.':'Partial comparison: missing/pending/running cells remain visible.',``,`Provisional references only. No statistical accuracy or winner conclusion.`,``,`| Model | Planned | Valid | Failed | Missing/pending | Attempts | Cost USD | Attempt median ms | Cell active median ms |`,`|---|---:|---:|---:|---:|---:|---:|---:|---:|`];for(const s of r.summaries)lines.push(`| ${s.model} | ${s.plannedCells} | ${s.validCells} | ${s.failedCells} | ${s.missingCells} | ${s.attempts} | ${money(s.totalCostNano)} | ${s.attemptLatencyMedianMs??'unknown'} | ${s.cellActiveLatencyMedianMs??'unknown'} |`);lines.push('',r.kind.startsWith('reader')?'| Case | Model | State | Provisional agreement | Historical / approved replay |':'| Case | Model | State | Definite matched / missing | Optional / other exact / rejected |','|---|---|---|---|---|');for(const row of r.rows)lines.push(r.kind.startsWith('reader')?`| ${row.caseId} | ${row.model} | ${row.state} | ${row.provisionalAgreement===null?'unavailable':String(row.provisionalAgreement)} | ${row.replay?row.replay.historicalNotePolicy.ruleId+' / '+row.replay.approvedNotePolicy.ruleId:'unavailable'} |`:`| ${row.caseId} | ${row.model} | ${row.state} | ${row.headingQuality?row.headingQuality.definiteMatched.length+' / '+row.headingQuality.definiteMissing.length:'unavailable'} | ${row.headingQuality?[row.headingQuality.optionalMatched.length,row.headingQuality.otherExactLines.length,row.headingQuality.rejected.length].join(' / '):'unavailable'} |`);lines.push('','Measured cell active latency excludes waits; it is not wall-clock duration.','',...r.limitations.map(v=>'- '+v));return lines.join('\n')+'\n';}
async function main(){const [manifest,status,reference,output]=process.argv.slice(2);requireThat(output,'Usage: report.mjs <manifest.json> <status-snapshot.json> <frozen-reference.json> <new-private-output.json>');assertPrivateOutput(output);const md=output.replace(/\.json$/i,'')+'.md';assertPrivateOutput(md);const report=await buildReport(manifest,status,reference);await writeFile(output,JSON.stringify(report,null,2)+'\n',{flag:'wx'});await writeFile(md,markdown(report),{flag:'wx'});console.log(JSON.stringify({output,markdown:md,complete:report.complete,models:report.summaries.map(s=>({model:s.model,valid:s.validCells,planned:s.plannedCells,costNano:s.totalCostNano})),networkCalls:0}));}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)await main();

