/**
 * Copy group `categories` (SPEC §6.5): the Categories page, the editor and the review before activation.
 * DOM-free, and never imports `copy.ts`: that file imports this one.
 */
export const categoriesCopy = {
  review: 'Review changes',
  startUsing: 'Start using these categories',
  activate: 'Activate these categories',
  keepCertainty: 'Keep the current filing certainty',
  nextAnswers: 'Next: your answers',

  title: 'Categories',
  lead: 'The categories every new run sorts documents into, in your own words. Both checks read these definitions.',
  edit: 'Edit categories',
  none: 'No categories are active yet.',
  readOnly: 'You can read the categories. Only a category editor can change them.',
  gitMode: 'Categories for this app are set outside the app, so they can’t be edited here.',
  drafts: 'Drafts not activated yet',
  openDraft: 'Open',
  activeSince: (when: string) => `Active since ${when}`,
  versionSince: (version: number, when: string) => `Version ${version} · active since ${when}`,
  versionNote: 'New runs use this version. Earlier runs keep the version they were sorted with.',
  draftOf: (when: string) => `Draft saved ${when}`,
  /** The two folders every run has besides the categories (core/domain/decision.ts). */
  folderLegend: [
    ['Needs review', 'folder human_review: the systems disagreed or weren’t certain enough.'],
    ['Could not process', 'folder could_not_process: a step failed, for example a scanned file with no text.']
  ],
  noneLegend: (name: string) => `Documents that fit no category (“${name}”) also go to Needs review.`,

  editingEyebrow: (version: number) => `Editing · draft of version ${version}`,
  editingFirst: 'Editing · your first categories',
  editorTitle: 'Edit categories',
  editorLead: 'Write what belongs in each category and what doesn’t. Saving creates a draft for review; nothing changes for new runs until you activate it.',
  name: 'Name',
  folder: 'Folder',
  folderLater: 'Made from the name when saved',
  noneTitle: 'When nothing fits',
  what: 'What belongs here',
  whatHint: 'Describe the purpose of these documents: what a reader does with them.',
  notFor: 'What doesn’t belong here',
  notForHint: 'Name the neighbouring category it could be confused with, and say what tells them apart.',
  examples: 'Examples, one per line (at least one)',
  add: 'Add a category',
  suggestedTitle: 'New folders from your review',
  suggestedLead: 'You made these folders while checking a run. Each can become a category once you describe it.',
  addSuggested: (name: string) => `Add '${name}' as a category`,
  remove: 'Remove this category',
  noneName: 'Name for documents that fit no category',
  noneWhat: 'When no category applies',
  saved: 'Saved. Check the changes before they are used.',
  needOne: 'Add at least one category.',
  needName: 'Give every category a name.',
  needDistinct: (name: string) => `Two categories are called '${name}'. Give each a different name.`,
  needWhat: (name: string) => `Say what belongs in '${name}'.`,
  needNotFor: (name: string) => `Say what doesn't belong in '${name}', and which category it is easily confused with.`,
  needExample: (name: string) => `Add at least one example for '${name}'.`,
  needNone: 'Fill in the name and meaning for documents that fit no category.',

  reviewEyebrow: (version: number) => `Review · draft of version ${version}`,
  reviewFirst: 'Review · your first categories',
  reviewTitle: 'Review category changes',
  reviewLead: 'These definitions are used for every new run once you activate them. Runs already made keep the categories they had.',
  changedCount: (n: number) => (n === 1 ? '1 category changed.' : `${n} categories changed.`),
  highlightBefore: 'Changes are',
  highlightWord: 'highlighted',
  highlightAfter: '; removed words are struck through. Activating affects new runs only.',
  unchanged: 'unchanged',
  changesTitle: 'What changes',
  changesKey: 'Added words are underlined. Removed words are struck through.',
  statusAdded: 'Added',
  statusRemoved: 'Removed',
  statusChanged: 'Changed',
  shownName: 'Name shown on the website',
  reordered: 'The categories are in a different order, which counts as a change of meaning.',
  noChanges: 'Nothing has changed compared with the categories in use.',
  draftTitle: 'All categories in this draft',
  certaintyReset: 'Because the definitions changed, automatic filing starts again at 90% certainty for these categories.',
  certaintyKept: 'The meaning of the categories has not changed, so automatic filing keeps its current certainty.',
  keepCertaintyHint: 'Only keep the current filing certainty if the meaning of the categories has not changed.',
  activated: 'These categories are now in use for new runs.',
  nextDocuments: 'Next: add documents',
  stale: 'The categories changed since this draft was made. Your edits are kept; open the editor again.',
  backToEditing: 'Back to editing',
  notFound: 'This draft could not be found.'
} as const;
