/** All words for the explicit two-configuration comparison. */
import { FAKE_VENDORS_SENTENCE } from '../vendors/outbound.ts';
export const bakeoffCopy = {
  simulated: FAKE_VENDORS_SENTENCE,
  title: 'Compare configurations',
  lead: 'Run the same selected documents twice against your saved answers. Each run needs its own spending decision and Start action.',
  unchanged: 'Nothing here changes the settings used for other runs. No result is adopted automatically.',
  open: 'Compare configurations',
  baseline: 'Baseline', candidate: 'Alternative',
  frozen: 'The settings and selected readings are fixed for this comparison.',
  chooseChange: 'Choose one change', chooseSource: 'Choose a local collection',
  chooseDocuments: 'Select documents for both runs', noneSelected: 'Select at least one document.',
  chooseCandidate: 'Choose an alternative before preparing the comparison.',
  sourceNeeded: 'Choose a collection saved on this computer.',
  readFolder: 'Read a source folder for this comparison',
  sources: 'Refresh local collections',
  source: (number: number, count: number) => `Local collection ${number} · ${count} documents`,
  readCollection: 'Read the selected local collection',
  selectAll: 'Select all', clearSelection: 'Clear selection',
  selected: (count: number) => `${count} documents selected for each run`,
  effort: (value: string) => `Reader effort: ${value}`,
  contractExact: 'Reader answers: evidence for every category',
  contractCompact: 'Reader answers: evidence for positive categories and near misses',
  confidenceSingle: 'Confidence questions: one request',
  confidenceGrouped: 'Confidence questions: grouped requests',
  prepare: 'Prepare both local drafts', preparing: 'Checking the selected readings…',
  prepared: 'Both local drafts are ready. Open the baseline spending confirmation first.',
  baselineFirst: 'Start the baseline first. The alternative still needs its own spending confirmation.',
  confirmArm: (name: string) => `Review spending for ${name.toLowerCase()}`,
  openRun: (name: string) => `Open ${name.toLowerCase()} run`,
  back: 'Back to this comparison', refresh: 'Check comparison results',
  checking: 'Reading both runs…', checked: 'The comparison has been checked.',
  notStarted: 'Not started', classificationComplete: 'Both runs have an outcome for every selected document.',
  incomplete: 'This comparison is incomplete. Missing outcomes are not counted as correct.',
  costs: 'Known spending', costUnresolved: 'Some charges are unresolved. Known spending is not the final cost.',
  costUnstarted: 'Combined cost is unavailable until both runs have recorded spending.',
  separateLimits: 'The two spending limits are independent. Their combined known spending is not a shared limit.',
  variation: 'Both complete pipelines run independently, including any heading recovery. Model answers can vary between runs; this comparison alone does not establish what caused a difference.',
  noAnswers: 'Save your answers before comparing configurations.',
  stale: 'The active categories, settings, build or filing requirement changed. Prepare a new comparison. These saved inputs have not been refreshed.',
  missing: 'The complete selected readings are not available unchanged on this computer. Explicitly reselect a matching local collection. Changed readings need a new comparison.',
  sameContent: 'Some files in this collection have the same content as another file in it. Remove the extra copies from the folder, then read the folder again.',
  recover: 'Restore missing readings from the selected collection',
  recovered: 'Matching readings are available again. Each run keeps its original confirmation.',
  recoveryHelp: 'Select a local collection above to restore missing readings. Only exactly matching readings can be used.',
  locked: 'This comparison’s selection is fixed. Prepare a new comparison to change it.',
  failedReading: 'Could not read',
  skipPilot: 'Run this selection without a trial',
  pilotRequired: (size: number) => `Selections above ${size} documents require the explicit choice to run without a trial.`,
  pilotSkipped: 'Trial explicitly skipped for both runs.',
  planned: 'Selected documents', completed: 'Recorded outcomes', missingOutcomes: 'Missing outcomes',
  uploaded: 'Readings received', pending: 'Received, awaiting an outcome',
  filed: 'Filed', review: 'Needs review', failed: 'Could not process',
  wrong: 'Incorrectly filed',
  ambiguous: 'More than one acceptable category', excluded: 'Excluded by you', unconfirmed: 'Not confirmed',
  outside: 'Saved answers outside this selection', noReference: 'Selected documents without saved answers',
  referenceTotal: 'All saved answers', sourceFailures: 'Failures in the saved answers',
  precision: 'Correct among scored automatic filings', reviewLoad: 'Review among all selected documents',
  of: (count: number, total: number) => `${count} of ${total}`,
  unknownCharges: 'Attempts with an unknown charge', pendingCharges: 'Charges awaiting accounting',
  combinedKnown: 'Combined known spending', results: 'Comparison results',
  paired: 'Documents with both outcomes', changedOutcomes: 'Different outcomes', sameOutcomes: 'Matching outcomes',
  documentResults: 'Selected document outcomes', document: 'Document',
  missingOutcome: 'No outcome recorded', noMeasuredTime: 'No measured duration available', duration: 'Measured duration',
  measured: (seconds: number) => `${seconds} seconds`,
  referenceMissing: 'Every selected document must have an entry in these saved answers. Choose a matching collection and selection.',
  details: {
    title: 'Configuration details', baseline: 'Frozen baseline', candidate: 'Selected change',
    experiment: 'Experiment id', manifestHash: 'Prepared input manifest hash', planHash: 'Frozen plan hash',
    reading: 'Reading/parser versions, notes and failures are included in each SHA-256 upload hash.',
  },
} as const;
