export const trialCopy = {
 selectionPending:'This run is being confirmed or has already started. Its selection and spending cannot change now.',
 search:'Search original documents',applySelection:'Use this selection',selectionFrozen:'This run has already been confirmed.',reviewClosed:'This trial review is confirmed and cannot be changed.',recording:'Recording your verdict...',reviewEvery:'Mark every automatically filed document right or wrong first.',
 serviceFact:'Model services',roleFact:'Run type',
 skipAction:'Use all documents without a trial',useTrial:'Return to a small trial',withoutTrial:'Without a reviewed trial',
 skipNote:'This run will start without a reviewed trial. Its history and results will record that choice. Check the document count and spending limit before starting.',
 readerFact:'Reader answer format',confidenceFact:'Confidence questions',
 readerContracts:{'reader-exact-evidence-v2':'Explanations for every category','reader-compact-verdicts-v1':'Explanations for matches and selected near misses'},
 confidencePolicies:{'confidence-single-request-v1':'One question set','confidence-grouped-nouls-v1':'Grouped question sets'},
 selectionTitle:'Choose what this run will read',
 collection:(n:number)=>String(n)+' documents in the original collection.',
 small:'Small run',trial:'Small trial',full:'Full run',
 ordinary:'Classify the selected documents as a small run',
 chooseTrial:'Start with a small trial, even for one document',
 chooseTrialNote:'Check a few results before paying for the rest.',
 selected:(n:number,total:number)=>String(n)+' of '+String(total)+' documents selected for this run.',
 first:(n:number)=>'Start with the first '+String(n)+' documents in the original selection order.',
 max:(n:number)=>'Choose between 1 and '+String(n)+' documents for the trial.',
 choose:'Choose documents',selectAll:'Select all originals',fullNote:'The full run starts with all originals selected, including the trial documents. Every selected document is classified and charged again. Earlier trial results stay in their own run.',
 keepCollection:'The original collection stays available on this computer.',
 savedSelection:'Selection saved. Check the document count and choose this run\'s spending limit.',
 empty:'Choose at least one document.',
 missingCollection:'The original collection is not available in this browser. Choose the originals again in a new run.',
 reviewTitle:'Review the small trial',reviewLead:'Check every automatically filed document against both systems\' reasoning and the original. Mark each placement right or wrong.',
 right:'Right',wrong:'Wrong',unreviewed:'Not reviewed yet',reviewed:'Your verdict is recorded.',confirm:'Confirm the trial',confirmed:'Your confirmation is recorded. Nothing else has started.',
 confirmNote:'Confirm only after reviewing every automatically filed document. This records your decision; it does not start another run.',
 zero:'The trial filed no documents automatically. Review its other outcomes before deciding whether to continue. Your explicit confirmation is still required.',
 complete:(right:number,total:number)=>String(right)+' of '+String(total)+' automatic placements marked right.',
 wrongNote:'A placement was marked wrong. Review its evidence in the editor, activate your revised categories, then start a new trial.',
 stale:'The categories changed after this trial. Start a new trial on the current categories.',
 editor:'Open the editor with this document\'s evidence',editorEvidence:'Evidence from the small trial',editorNote:'This evidence is a reference while you edit. No wording or example is added automatically.',
 newTrial:'Prepare a new trial',prepareFull:'Prepare the full run',prepared:'The next run is prepared locally. Check its selection and confirm spending before starting.',
 readAgain:'Read the trial review again',returnTrial:'Back to the trial',notFinished:'This trial has not produced an outcome for every document. A discarded incomplete trial cannot unlock a full run.',
 newTrialReference:'A new trial on changed categories starts without the earlier saved-answer link. Reconnect confirmed answers through the review flow if needed.',
 vendors:{fake:'Pretend models - test results and simulated costs',live:'Live models - real calls and costs',unknown:'Model service identity is not recorded'},
 role:{pilot:'Small trial',full:'Full run'},
 details:{campaign:'Campaign',pilot:'Pilot'},
} as const;
